### PR TITLE
feature-async-actions

### PR DESCRIPTION
**Pull request by davemoore-**
Converted blocking requests to async requests. Integration tests now run with assertions enabled in the Elasticsearch JVM.

### CODE REVIEW

**Comment by davemoore-** [comment]
> I think `CompletableFuture#join` will still block on the calling thread. I ran into this issue in our fork when using `CompletableFuture#get`. We might need to use the [`CompletableFuture#thenCompose`](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/CompletableFuture.html#thenCompose-java.util.function.Function-) method to queue up more async work after this one finishes.

You're right, I just ran our stress test script and saw the cluster hang, even though the assertions weren't thrown.

I suspect your forks of ResolutionAction and Job are closer to a proper solution than mine, because you have already been refactoring them to consider async (e.g. with bulk actions). Do you believe you are close to a solution on your fork? If so, I can assign this issue to you to bring it to resolution, and I can help merge it upstream.

**Comment by davemoore-** [comment]
Update:

Today I committed to refactoring the Job class to support async actions.

- The Job class now implements async actions without the use of `CompletableFuture` [as advised](https://discuss.elastic.co/t/what-is-the-proper-design-pattern-for-plugins-that-must-submit-multiple-requests-to-elasticsearch/262190/14) by David Turner (Elasticsearch engineer).
- Integration tests are passing with assertions enabled.
- Multi-node stress tests are passing without hanging the cluster (#56).
- Performance appears to be the same as before the refactor.

Here are the key diffs that relate to #56:

- `ResolutionAction.runJob()` now calls `Job.run()` and passes an `ActionListener` that sends the eventual output of the job to the user ([diff](https://github.com/zentity-io/zentity/pull/67/commits/c267fcf21f2168a8c944a77556aeac3ee3fc5387#diff-da0319b8e296349a48a69589e0a8e0741938515bcc9e6fdcf59270ac56fe3828)).
- `Job.run()` passes that `ActionListener` to `Job.traverse()` ([diff](https://github.com/zentity-io/zentity/pull/67/commits/c267fcf21f2168a8c944a77556aeac3ee3fc5387#diff-f0157aff5b741656786bef437bb41ce170eaba293f8ba212ced5e1f4315ae6a8L1542-L1579)).
- `Job.traverse()`, being recursive, continues to pass that `ActionListener` until the job eventually completes or fails, at which point the listener is invoked and a response is sent to the user.

The remainder of the diff is implementation details. I moved a huge chunk of code from the Job class to a new Query class, which helped break up the massive nested loop of `Job.traverse()`. Generally, the Query class now handles the "pre-search" processing originally handled by `Job.traverse()`, and a new method called `Job.onSearchComplete()` now handles the "post-search" processing. The Query class builds and executes the Elasticsearch query, then calls `Job.onSearchComplete()`, which then calls `Job.traverse()`. This leaves `Job.traverse()` functioning mostly to queue up new Queries as needed, and to determine if the job has completed.

**Comment by davemoore-** [comment]
I'm going to merge this into master soon to confirm that the patch jives with the recent changes to the test framework.

**Comment by austince** [comment]
> I'm going to merge this into master soon to confirm that the patch jives with the recent changes to the test framework.

Fingers crossed! Another option might be to [rebase onto master and force push](https://blog.developer.atlassian.com/force-with-lease/) to this branch to have the changes + CI configurations pulled in.

**Comment by davemoore-** [comment]
Merged, but I'm going to review everything on master. I had to resolve a few conflicts.

**Comment by davemoore-** [comment]
So far the current state on master looks good. I'm going to do some manual acceptance testing before making the patch release official. Should be done tonight if all goes well.

The [commit history](https://github.com/zentity-io/zentity/commits/master) has a bunch of duplicate commits after merging the PRs. Trying to figure out what happened there. The first two PRs were simple "Rebase and Merge" in Github -- no conflicts. Here's what happened for this PR:

On IntelliJ:

- While on `feature-async-actions` select `origin/master` > "Rebase Current Onto Selected"
- Resolved merge conflicts
- Committed and pushed to `feature-async-actions`

Then on Github:

- PR disallowed "Rebase and Merge" due to conflicts
- Resolved conflicts on GitHub UI and comitted changes
- PR still disallowed "Rebase and Merge," but allowed "Merge pull request," which I selected.

**Pull request merged**
